server:
  port: 8080

spring:
  application.name: gateway
  cloud:
    gateway:
      default-filters:
      - PrefixPath=/
      routes:
      # ============================
      - id: flashcard
        uri: lb://flashcard
        predicates:
        - Path=/flashcard/**
        filters:
        - RewritePath=/flashcard(?<segment>/?.*), /$\{segment}
      # ============================
      - id: quiz
        uri: lb://quiz
        predicates:
        - Path=/quiz/**
         filters:
         - RewritePath=/quiz(?<segment>?.*), $\{segment}
    config:
      discovery:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
